### PR TITLE
Rename sketch to match folder name

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE requires the sketch folder name to match the filename of the primary sketch file. This change causes the example sketch to be accessible via the Arduino IDE's File > Examples > LIBRARYNAME menu after the library is installed.

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#library-examples

### CODE REVIEW

**Comment by jimaobian** [comment]
Thank you!
fixed in version 1.0.3

**Comment by per1234** [comment]
@jimaobian you didn't fix it. The folder name is still **G**etStarted and the file name is **g**etStarted: https://github.com/DFRobot/DFRobotDFPlayerMini/tree/master/examples/GetStarted. On a case-sensitive OS like Linux, the case of the folder and filename must match in order for the sketch to be recognized by the Arduino IDE.

**Comment by jimaobian** [comment]
Sorry guy! It's my problem. I'm using Mac and it is case insensitive. I'll try to fix it in 1.0.4.
Thank you for your feed back

**Comment by per1234** [comment]
I didn't know that about Mac. I've never used one but I assumed they would be case sensitive like Linux. I usually use Windows so the case changes are a bit tricky for me also.

You might be interested to know that you can simply click the "Merge pull request" button on a pull request to accept the proposed changes to your repository. This is much easier and less prone to errors than trying to reproduce the changes yourself. For more information, see:
https://help.github.com/articles/merging-a-pull-request/
Of course, you're welcome to manage your project as you see fit. What's important to me is that the problem is resolved, rather than how it's resolved.

**Comment by jimaobian** [comment]
Update! Thank you @per1234

**Pull request closed without merging**
